apiVersion: v1
kind: ConfigMap
metadata:
  name: planmate-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DB_URL: "jdbc:postgresql://postgres-service:5432/postgres"
  IMG_URL: "/app/images/googleplace/"
