apiVersion: v1
kind: ConfigMap
metadata:
  name: planmate-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_HOST: "planmate-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  DB_URL: "jdbc:p6spy:postgresql://planmate-db-rw:5432/planmate"
  STORAGE_TYPE: "minio"
  MINIO_ENDPOINT: "http://planmate-minio.default.svc.cluster.local:9000"
  MINIO_BUCKET: "planmate-images"
  GOOGLE_GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent"
  TZ: "Asia/Seoul"
