apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planmate-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-hide-headers: "Content-Security-Policy"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self' 'unsafe-eval' 'unsafe-inline' https://static.cloudflareinsights.com blob: data:;";
spec:
  tls:
  - hosts:
    - pmserver1.salmakis.online
    secretName: planmate-backend-tls
  rules:
  - host: pmserver1.salmakis.online
    http:
      paths:
      - path: /minio(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-console
            port:
              number: 9090
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: planmate-backend-service
            port:
              number: 80