apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planmate-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
    - pmserver1.salmakis.online
    - minio.salmakis.online
    - redis.salmakis.online
    - db.salmakis.online
    secretName: planmate-backend-tls
  rules:
  - host: minio.salmakis.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-console
            port:
              number: 9090
  - host: redis.salmakis.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redisinsight-service
            port:
              number: 80
  - host: db.salmakis.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-service
            port:
              number: 80
  - host: pmserver1.salmakis.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: planmate-backend-service
            port:
              number: 80