apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planmate-backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - pmserver.salakis.online
    secretName: planmate-backend-tls
  rules:
  - host: pmserver.salakis.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: planmate-backend-service
            port:
              number: 80