apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.2.1
    helm:
      parameters:
        # --- [추가된 부분] 이미지 다운로드 에러 방지용 ---
        - name: image.tag
          value: "7.4"
        - name: sentinel.image.tag
          value: "7.4"
        # ---------------------------------------------
        - name: fullnameOverride
          value: "redis"
        - name: architecture
          value: replication
        - name: sentinel.enabled
          value: "true"
        - name: sentinel.masterSet
          value: "mymaster"
        - name: auth.password
          value: "redis1234"     # 문자열 처리 Good!
        # 리소스 제한 (요청하신 부분)
        - name: master.resources.requests.cpu
          value: "50m"           # 용량 축소 Good!
        - name: master.resources.limits.cpu
          value: "200m"
        - name: replica.resources.requests.cpu
          value: "50m"
        - name: replica.resources.limits.cpu
          value: "200m"
        - name: sentinel.resources.requests.cpu
          value: "50m"
        - name: sentinel.resources.limits.cpu
          value: "100m"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true