apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.2.1
    helm:
      parameters:
        # --- [수정된 부분] 확실히 존재하는 태그로 변경 ---
        - name: image.tag
          value: "7.2.5-debian-12-r0"
        - name: sentinel.image.tag
          value: "7.2.5-debian-12-r0"
        # ---------------------------------------------
        - name: fullnameOverride
          value: "redis"
        - name: architecture
          value: replication
        - name: sentinel.enabled
          value: "true"
        - name: sentinel.masterSet
          value: "mymaster"
        - name: auth.password
          value: "redis1234"
        # 리소스 제한
        - name: master.resources.requests.cpu
          value: "50m"
        - name: master.resources.limits.cpu
          value: "200m"
        - name: replica.resources.requests.cpu
          value: "50m"
        - name: replica.resources.limits.cpu
          value: "200m"
        - name: sentinel.resources.requests.cpu
          value: "50m"
        - name: sentinel.resources.limits.cpu
          value: "100m"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true